sudo: required
services:
  - docker

before_install:
  - docker build -t ozekidesu/docker-react -f dockerfile.dev .
### try again
script:
  - docker run -e CI=true ozekidesu/docker-react npm run test